name: "Fetch Sources"
description: "Download and unpack multiple sources (git/zip/tar)"
inputs:
  sources:
    description: "List of sources (comma or JSON array)"
    required: true
  dest:
    description: "Destination directory"
    required: true
  type:
    description: "Type of source: git, zip, tar, auto"
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: Run download_URLS_files.sh
      run: bash "${{ github.action_path }}/../../../scripts/download_URLS_files.sh" \
           -s "${{ inputs.sources }}" \
           -d "${{ inputs.dest }}" \
           -t "${{ inputs.type }}"
      shell: bash
