[build-system]
requires = [
    "setuptools>=42",
    "pybind11",
    "wheel",
]
# 指定使用哪个后端来构建包，这里是 setuptools.build_meta，表示使用 setuptools 的现代构建 API。
build-backend = "setuptools.build_meta" 

[project]
name = "project_study"
version = "0.0.4"