name: Use reusable build workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # ✅ 必须加上，否则 release 上传会被拒绝

jobs:
  call-build:
    uses: HurleyKane/project_template/.github/workflows/template-python-build-release.yml@master
    with:
      python-version: '["3.11"]'
      build-command: "python -m build"
      download-dependencies: "https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.tar.gz"
      download-dependencies-path: "third_party"
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
