name: Test Setup Dependency Action

on:
  workflow_dispatch:

jobs:
  test-dependency:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout this repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ 下载并解压一个 zip 包
      - name: Download Eigen (zip)
        uses: ./.github/actions/setup-dependency
        with:
          sources: '[
              "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip",
              "https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.zip",
            ]
          dest: "./deps"
          type: "auto"

      # 3️⃣ 下载并解压一个 tar.gz 包
      - name: Download Catch2 (tar.gz)
        uses: ./.github/actions/setup-dependency
        with:
          sources: "https://github.com/catchorg/Catch2/archive/refs/tags/v3.3.2.tar.gz"
          dest: "./deps"
          type: "auto"

      # 4️⃣ Clone 一个 git 仓库
      - name: Clone fmt library
        uses: ./.github/actions/setup-dependency
        with:
          sources: "https://github.com/fmtlib/fmt.git"
          dest: "deps"
          type: "git"

      - name: list deps directory
        run: |
          echo "pwd is : $(pwd)"
          ls -R deps